const companies = [
  {
    symbol: "ABT",
    name: "正直",
    backgroundColor: "#0096D7",
    textColor: "white",
  },
  {
    symbol: "ABBV",
    name: "勇敢",
    backgroundColor: "#00003A",
    textColor: "white",
  },
  {
    symbol: "ABMD",
    name: "仗义",
    backgroundColor: "#3b818c",
    textColor: "white",
  },
  {
    symbol: "ACN",
    name: "稳重",
    backgroundColor: "#bbb5ac",
    textColor: "white",
  },
  {
    symbol: "ATVI",
    name: "沉稳",
    backgroundColor: "#193A5B",
    textColor: "white",
  },
  {
    symbol: "ADBE",
    name: "体面",
    backgroundColor: "#ED1C24",
    textColor: "white",
  },
  {
    symbol: "AMD",
    name: "懂礼",
    backgroundColor: "#023D2F",
    textColor: "white",
  },
  {
    symbol: "AAP",
    name: "礼貌",
    backgroundColor: "#008FFE",
    textColor: "white",
  },
  {
    symbol: "AES",
    name: "高尚",
    backgroundColor: "#157FC4",
    textColor: "white",
  },
  {
    symbol: "AFL",
    name: "真诚",
    backgroundColor: "#00A7E1",
    textColor: "white",
  },
  {
    symbol: "A",
    name: "诚信",
    backgroundColor: "#3170a7",
    textColor: "white",
  },
  {
    symbol: "APD",
    name: "谦虚",
    backgroundColor: "#009539",
    textColor: "white",
  },
  {
    symbol: "AKAM",
    name: "虚心",
    backgroundColor: "#252969",
    textColor: "white",
  },
  {
    symbol: "ALK",
    name: "忠心",
    backgroundColor: "#00426A",
    textColor: "white",
  },
  {
    symbol: "ALB",
    name: "正义感",
    backgroundColor: "#008676",
    textColor: "white",
  },
  {
    symbol: "ALXN",
    name: "忠贞",
    backgroundColor: "#002898",
    textColor: "white",
  },

  {
    symbol: "ZBH",
    name: "助人",
    backgroundColor: "#1081C5",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "乐观",
    backgroundColor: "#451400",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "友善",
    backgroundColor: "#01C1D6",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "热情",
    backgroundColor: "#BA0C2F",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "温柔",
    backgroundColor: "#0982C6",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "幽默",
    backgroundColor: "#153869",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "活泼",
    backgroundColor: "#FF1900",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "好学",
    backgroundColor: "#1BA0D7",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "友好",
    backgroundColor: "#003A72",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "无私",
    backgroundColor: "#00A271",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "热心",
    backgroundColor: "#de1c31",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "认真",
    backgroundColor: "#0480CA",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "执着",
    backgroundColor: "#007AC2",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "自信",
    backgroundColor: "#002F6C",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "阳光",
    backgroundColor: "#1E3930",
    textColor: "white",
  },
  {
    symbol: "ZTS",
    name: "坚韧",
    backgroundColor: "#0099D8",
    textColor: "white",
  },
  {
    symbol: "MMM",
    name: "善良",
    backgroundColor: "#EE1B2D",
    textColor: "white",
  },
  {
    symbol: "ShangJin",
    name: "上进",
    backgroundColor: "#022C6C",
    textColor: "white",
  },
  {
    symbol: "DaFang",
    name: "大方",
    backgroundColor: "#1B77F2",
    textColor: "white",
  },
  {
    symbol: "deti",
    name: "得体",
    backgroundColor: "#0D5DB8",
    textColor: "white",
  },
  {
    symbol: "lvji",
    name: "律己",
    backgroundColor: "#0042C2",
    textColor: "white",
  },
  {
    symbol: "aiguo",
    name: "爱国",
    backgroundColor: "#104F8C",
    textColor: "white",
  },
  {
    symbol: "jingye",
    name: "敬业",
    backgroundColor: "#C11A1C",
    textColor: "white",
  },
  {
    symbol: "kuanrong",
    name: "宽容",
    backgroundColor: "#29445A",
    textColor: "white",
  },
  {
    symbol: "youzhi",
    name: "有志",
    backgroundColor: "#013C81",
    textColor: "white",
  },
  {
    symbol: "qinfen",
    name: "勤奋",
    backgroundColor: "#FF1900",
    textColor: "white",
  },
  {
    symbol: "keku",
    name: "刻苦",
    backgroundColor: "#015A98",
    textColor: "white",
  },
  {
    symbol: "yinren",
    name: "隐忍",
    backgroundColor: "#FCE24C",
    textColor: "white",
  },
  {
    symbol: "yuedu",
    name: "阅读",
    backgroundColor: "#081135",
    textColor: "white",
  },
  {
    symbol: "ganjing",
    name: "干净",
    backgroundColor: "#5D5D5F",
    textColor: "white",
  },
  {
    symbol: "kaixin",
    name: "开心",
    backgroundColor: "#ff571a",
    textColor: "white",
  },
  {
    symbol: "zhengjie",
    name: "整洁",
    backgroundColor: "#F1471D",
    textColor: "white",
  },
  {
    symbol: "jishan",
    name: "和善",
    backgroundColor: "#63A844",
    textColor: "white",
  },
  {
    symbol: "daqi",
    name: "大气",
    backgroundColor: "#EC1944",
    textColor: "white",
  },
  {
    symbol: "jiankang",
    name: "健康",
    backgroundColor: "#5dbe8a",
    textColor: "white",
  },
  {
    symbol: "ganen",
    name: "感恩",
    backgroundColor: "#2C6CBE",
    textColor: "white",
  },
  {
    symbol: "zhientubao",
    name: "知恩图报",
    backgroundColor: "#006491",
    textColor: "white",
  },
  {
    symbol: "youmengxiang",
    name: "有梦想",
    backgroundColor: "#004C9A",
    textColor: "white",
  },
  {
    symbol: "zhixianjue",
    name: "知先觉",
    backgroundColor: "#00477F",
    textColor: "white",
  },
  {
    symbol: "zhiren",
    name: "知人",
    backgroundColor: "#E22739",
    textColor: "white",
  },
  {
    symbol: "DanDing",
    name: "淡定",
    backgroundColor: "#1B77F2",
    textColor: "white",
  },
  {
    symbol: "zhimian",
    name: "知面",
    backgroundColor: "#ED1B2F",
    textColor: "white",
  },
  {
    symbol: "zhixin",
    name: "知心",
    backgroundColor: "#1175C7",
    textColor: "white",
  },
  {
    symbol: "zhishi",
    name: "知识",
    backgroundColor: "#2775b6",
    textColor: "white",
  },
  {
    symbol: "zhili",
    name: "知礼",
    backgroundColor: "#0098CC",
    textColor: "white",
  },
  {
    symbol: "zhidao",
    name: "知道",
    backgroundColor: "#0f59a4",
    textColor: "white",
  },
  {
    symbol: "youdandang",
    name: "有担当",
    backgroundColor: "#827A71",
    textColor: "white",
  },
  {
    symbol: "dajuguan",
    name: "大局观",
    backgroundColor: "#A0ACBC",
    textColor: "white",
  },
  {
    symbol: "shijieguan",
    name: "世界观",
    backgroundColor: "#EF3E42",
    textColor: "white",
  },
  {
    symbol: "fenxiang",
    name: "分享",
    backgroundColor: "#E21D38",
    textColor: "white",
  },
  {
    symbol: "shoufa",
    name: "守法",
    backgroundColor: "#FF0200",
    textColor: "white",
  },
  {
    symbol: "xinxiongkuanguang",
    name: "心胸宽广",
    backgroundColor: "#0D3469",
    textColor: "white",
  },
  {
    symbol: "bubeibukang",
    name: "不卑不亢",
    backgroundColor: "#F1651F",
    textColor: "white",
  },
  {
    symbol: "baizhebunao",
    name: "百折不挠",
    backgroundColor: "#EE3524",
    textColor: "white",
  },
  {
    symbol: "quanshenguanzhu",
    name: "全神贯注",
    backgroundColor: "#ED1B2D",
    textColor: "white",
  },
  {
    symbol: "guangmingleiluo",
    name: "光明磊落",
    backgroundColor: "#E21D38",
    textColor: "white",
  },
];
export default companies;
